application: trackmileage
version: 1
runtime: python
api_version: 1


handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /edit/.*
  script: handlers/edit.py
- url: /.*
  script: handlers/view.py
