application: trackmileagehr
version: 1
runtime: python27
threadsafe: true
api_version: 1

#builtins:
#- remote_api: on

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /edit/.*
  script: handlers.edit.editApp
- url: /.*
  script: handlers.view.mainApp
